[build]
  command = "npm run build"
  publish = "public"
  functions = "functions"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/contact/*"
  to = "/.netlify/functions/:splat"
  status = 200
